### ISSUE TITLE
dont see fr-CA

### ISSUE THREAD

**Issue by productdevbook** [Avansai/resolve-accept-language#4] opened 2022-11-20 07:18 UTC
![image](https://user-images.githubusercontent.com/38668796/202890586-f8278a8f-5424-4052-b080-2907ea6783e0.png)

**Comment by nbouvrette** [comment] 2022-12-05 00:06
Sorry for the late reply, I just saw this issue.

I suspect you have an issue with your environment. I just re-run the exact code you provided and I am getting the correct result (`fr-CA`). This example is also part of unit tests and is returning the correct value.

Do you mind providing more details on your environment as I am unable to reproduce the issue?

**Comment by nbouvrette** [comment] 2022-12-06 18:15
I'm going to close this as this is not reproducable - please comment back if you have more details on this issue.

**Closed by nbouvrette** 2022-12-06 18:15 UTC
Labels: question
